/*
 * MainFrame.java
 *
 * Created on 05-04-2011, 17:44:32
 */

package gui;

import gui.comm.CommFrame;
import gui.manualControl.ControlFrame;
import gui.processing.ProcessingFrame;
import control.FramePlaceHolder;

/**
 *
 * @author Morten Hulvej
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        
        makeCommFrame();
        
        FramePlaceHolder.setMainFrame(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        dashboard.setBackground(new java.awt.Color(204, 204, 204));

        fileMenu.setText("File");

        jMenuItem1.setText("jMenuItem1");
        fileMenu.add(jMenuItem1);

        mainMenuBar.add(fileMenu);

        jMenu2.setText("Edit");
        mainMenuBar.add(jMenu2);

        aboutMenu.setText("About");

        jMenuItem2.setText("jMenuItem2");
        aboutMenu.add(jMenuItem2);

        mainMenuBar.add(aboutMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Opretter og arrangerer alle vinduer
     * <br><br>(ImageProcessing,Comm,Path,manualControl)
     */
    public void makeAndArrangeFrames() {
    	// TODO
	}
    public void makeControlFrame() {
		// TODO
    	
    	ControlFrame controlFrame = new ControlFrame();
    	
    	controlFrame.setVisible(true);
    	dashboard.add(controlFrame);
	}
    /**
     * Opretter panel med funktioner vedr. al image-processing
     */
    public void makeProcessingFrame() {
    	ProcessingFrame processFrame = new ProcessingFrame();
    	
        processFrame.setLocation(dashboard.getSize().width - processFrame.getSize().width, processFrame.getLocation().y);

    	processFrame.setVisible(true);
    	dashboard.add(processFrame);
	}
    public void makePathfindingFrame() {
		// TODO
	}
    public void makeCommFrame() {
		// TODO
    	CommFrame commFrame = new CommFrame();
    	commFrame.setVisible(true);
    	
    	dashboard.add(commFrame);
	}
    public void arrangeFrames() {
		// TODO
	}
    public javax.swing.JDesktopPane getDashboard(){
    	return dashboard;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JDesktopPane dashboard;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mainMenuBar;
    // End of variables declaration//GEN-END:variables

}
