/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThresholdsFrame.java
 *
 * Created on 13-06-2011, 18:21:55
 */

package gui.processing;

/**
 *
 * @author Morten Hulvej
 */
public class ThresholdsFrame2 extends javax.swing.JInternalFrame {

    /** Creates new form ThresholdsFrame */
    public ThresholdsFrame2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        thresholdsLayeredPane = new javax.swing.JLayeredPane();
        robot1SettingsPanel = new javax.swing.JTabbedPane();
        robotFrontThresholdPanel = new javax.swing.JPanel();
        minRGBpanel = new javax.swing.JPanel();
        minRedSlider = new javax.swing.JSlider();
        minGreenSlider = new javax.swing.JSlider();
        minBlueSlider = new javax.swing.JSlider();
        minRVal = new javax.swing.JLabel();
        minGVal = new javax.swing.JLabel();
        minBVal = new javax.swing.JLabel();
        maxRGBpanel = new javax.swing.JPanel();
        maxRedSlider = new javax.swing.JSlider();
        maxBlueSlider = new javax.swing.JSlider();
        maxGreenSlider = new javax.swing.JSlider();
        maxRVal = new javax.swing.JLabel();
        maxGVal = new javax.swing.JLabel();
        maxBVal = new javax.swing.JLabel();
        robotBackThresholdPanel = new javax.swing.JPanel();
        minRGBpanel1 = new javax.swing.JPanel();
        minRedSlider1 = new javax.swing.JSlider();
        minGreenSlider1 = new javax.swing.JSlider();
        minBlueSlider1 = new javax.swing.JSlider();
        minRVal1 = new javax.swing.JLabel();
        minGVal1 = new javax.swing.JLabel();
        minBVal1 = new javax.swing.JLabel();
        maxRGBpanel1 = new javax.swing.JPanel();
        maxRedSlider1 = new javax.swing.JSlider();
        maxBlueSlider1 = new javax.swing.JSlider();
        maxGreenSlider1 = new javax.swing.JSlider();
        maxRVal1 = new javax.swing.JLabel();
        maxGVal1 = new javax.swing.JLabel();
        maxBVal1 = new javax.swing.JLabel();
        cakesThresholdPanel = new javax.swing.JPanel();
        minRGBpanel2 = new javax.swing.JPanel();
        minRedSlider2 = new javax.swing.JSlider();
        minGreenSlider2 = new javax.swing.JSlider();
        minBlueSlider2 = new javax.swing.JSlider();
        minRVal2 = new javax.swing.JLabel();
        minGVal2 = new javax.swing.JLabel();
        minBVal2 = new javax.swing.JLabel();
        maxRGBpanel2 = new javax.swing.JPanel();
        maxRedSlider2 = new javax.swing.JSlider();
        maxBlueSlider2 = new javax.swing.JSlider();
        maxGreenSlider2 = new javax.swing.JSlider();
        maxRVal2 = new javax.swing.JLabel();
        maxGVal2 = new javax.swing.JLabel();
        maxBVal2 = new javax.swing.JLabel();
        obstacleThresholdPanel = new javax.swing.JPanel();
        minRGBpanel3 = new javax.swing.JPanel();
        minRedSlider3 = new javax.swing.JSlider();
        minGreenSlider3 = new javax.swing.JSlider();
        minBlueSlider3 = new javax.swing.JSlider();
        minRVal3 = new javax.swing.JLabel();
        minGVal3 = new javax.swing.JLabel();
        minBVal3 = new javax.swing.JLabel();
        maxRGBpanel3 = new javax.swing.JPanel();
        maxRedSlider3 = new javax.swing.JSlider();
        maxBlueSlider3 = new javax.swing.JSlider();
        maxGreenSlider3 = new javax.swing.JSlider();
        maxRVal3 = new javax.swing.JLabel();
        maxGVal3 = new javax.swing.JLabel();
        maxBVal3 = new javax.swing.JLabel();
        miscPanel = new javax.swing.JPanel();
        robot2SettingsPanel = new javax.swing.JTabbedPane();
        robotFrontThresholdPanel1 = new javax.swing.JPanel();
        minRGBpanel4 = new javax.swing.JPanel();
        minRedSlider4 = new javax.swing.JSlider();
        minGreenSlider4 = new javax.swing.JSlider();
        minBlueSlider4 = new javax.swing.JSlider();
        minRVal4 = new javax.swing.JLabel();
        minGVal4 = new javax.swing.JLabel();
        minBVal4 = new javax.swing.JLabel();
        maxRGBpanel4 = new javax.swing.JPanel();
        maxRedSlider4 = new javax.swing.JSlider();
        maxBlueSlider4 = new javax.swing.JSlider();
        maxGreenSlider4 = new javax.swing.JSlider();
        maxRVal4 = new javax.swing.JLabel();
        maxGVal4 = new javax.swing.JLabel();
        maxBVal4 = new javax.swing.JLabel();
        robotBackThresholdPanel1 = new javax.swing.JPanel();
        minRGBpanel5 = new javax.swing.JPanel();
        minRedSlider5 = new javax.swing.JSlider();
        minGreenSlider5 = new javax.swing.JSlider();
        minBlueSlider5 = new javax.swing.JSlider();
        minRVal5 = new javax.swing.JLabel();
        minGVal5 = new javax.swing.JLabel();
        minBVal5 = new javax.swing.JLabel();
        maxRGBpanel5 = new javax.swing.JPanel();
        maxRedSlider5 = new javax.swing.JSlider();
        maxBlueSlider5 = new javax.swing.JSlider();
        maxGreenSlider5 = new javax.swing.JSlider();
        maxRVal5 = new javax.swing.JLabel();
        maxGVal5 = new javax.swing.JLabel();
        maxBVal5 = new javax.swing.JLabel();
        cakesThresholdPanel1 = new javax.swing.JPanel();
        minRGBpanel6 = new javax.swing.JPanel();
        minRedSlider6 = new javax.swing.JSlider();
        minGreenSlider6 = new javax.swing.JSlider();
        minBlueSlider6 = new javax.swing.JSlider();
        minRVal6 = new javax.swing.JLabel();
        minGVal6 = new javax.swing.JLabel();
        minBVal6 = new javax.swing.JLabel();
        maxRGBpanel6 = new javax.swing.JPanel();
        maxRedSlider6 = new javax.swing.JSlider();
        maxBlueSlider6 = new javax.swing.JSlider();
        maxGreenSlider6 = new javax.swing.JSlider();
        maxRVal6 = new javax.swing.JLabel();
        maxGVal6 = new javax.swing.JLabel();
        maxBVal6 = new javax.swing.JLabel();
        obstacleThresholdPanel1 = new javax.swing.JPanel();
        minRGBpanel7 = new javax.swing.JPanel();
        minRedSlider7 = new javax.swing.JSlider();
        minGreenSlider7 = new javax.swing.JSlider();
        minBlueSlider7 = new javax.swing.JSlider();
        minRVal7 = new javax.swing.JLabel();
        minGVal7 = new javax.swing.JLabel();
        minBVal7 = new javax.swing.JLabel();
        maxRGBpanel7 = new javax.swing.JPanel();
        maxRedSlider7 = new javax.swing.JSlider();
        maxBlueSlider7 = new javax.swing.JSlider();
        maxGreenSlider7 = new javax.swing.JSlider();
        maxRVal7 = new javax.swing.JLabel();
        maxGVal7 = new javax.swing.JLabel();
        maxBVal7 = new javax.swing.JLabel();
        miscPanel1 = new javax.swing.JPanel();
        robot1RadioButton = new javax.swing.JRadioButton();
        robot2RadioButton = new javax.swing.JRadioButton();
        commonPanel = new javax.swing.JPanel();
        bufzoneSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        obstacleThresholdPanel2 = new javax.swing.JPanel();
        minRGBpanel8 = new javax.swing.JPanel();
        minRedSlider8 = new javax.swing.JSlider();
        minGreenSlider8 = new javax.swing.JSlider();
        minBlueSlider8 = new javax.swing.JSlider();
        minRVal8 = new javax.swing.JLabel();
        minGVal8 = new javax.swing.JLabel();
        minBVal8 = new javax.swing.JLabel();
        maxRGBpanel8 = new javax.swing.JPanel();
        maxRedSlider8 = new javax.swing.JSlider();
        maxBlueSlider8 = new javax.swing.JSlider();
        maxGreenSlider8 = new javax.swing.JSlider();
        maxRVal8 = new javax.swing.JLabel();
        maxGVal8 = new javax.swing.JLabel();
        maxBVal8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        commonRadioButton = new javax.swing.JRadioButton();

        minRGBpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider.setMaximum(255);
        minRedSlider.setMinorTickSpacing(1);
        minRedSlider.setValue(0);

        minGreenSlider.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider.setMaximum(255);
        minGreenSlider.setMinorTickSpacing(1);
        minGreenSlider.setValue(70);

        minBlueSlider.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider.setMaximum(255);
        minBlueSlider.setMinorTickSpacing(1);
        minBlueSlider.setValue(0);

        javax.swing.GroupLayout minRGBpanelLayout = new javax.swing.GroupLayout(minRGBpanel);
        minRGBpanel.setLayout(minRGBpanelLayout);
        minRGBpanelLayout.setHorizontalGroup(
            minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal)
                    .addComponent(minGVal)
                    .addComponent(minBVal))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        minRGBpanelLayout.setVerticalGroup(
            minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal))
                .addGroup(minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal))
                .addGroup(minRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal)
                    .addComponent(minBlueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider.setMaximum(255);
        maxRedSlider.setMinorTickSpacing(1);
        maxRedSlider.setValue(70);

        maxBlueSlider.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider.setMaximum(255);
        maxBlueSlider.setMinorTickSpacing(1);
        maxBlueSlider.setValue(90);

        maxGreenSlider.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider.setMaximum(255);
        maxGreenSlider.setMinorTickSpacing(1);
        maxGreenSlider.setValue(255);

        javax.swing.GroupLayout maxRGBpanelLayout = new javax.swing.GroupLayout(maxRGBpanel);
        maxRGBpanel.setLayout(maxRGBpanelLayout);
        maxRGBpanelLayout.setHorizontalGroup(
            maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal)
                    .addComponent(maxGVal)
                    .addComponent(maxBVal))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        maxRGBpanelLayout.setVerticalGroup(
            maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal))
                .addGroup(maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal))
                .addGroup(maxRGBpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal)
                    .addComponent(maxBlueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout robotFrontThresholdPanelLayout = new javax.swing.GroupLayout(robotFrontThresholdPanel);
        robotFrontThresholdPanel.setLayout(robotFrontThresholdPanelLayout);
        robotFrontThresholdPanelLayout.setHorizontalGroup(
            robotFrontThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotFrontThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotFrontThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maxRGBpanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minRGBpanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        robotFrontThresholdPanelLayout.setVerticalGroup(
            robotFrontThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotFrontThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot1SettingsPanel.addTab("Front", robotFrontThresholdPanel);

        minRGBpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider1.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider1.setMaximum(255);
        minRedSlider1.setMinorTickSpacing(1);
        minRedSlider1.setValue(0);

        minGreenSlider1.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider1.setMaximum(255);
        minGreenSlider1.setMinorTickSpacing(1);
        minGreenSlider1.setValue(0);

        minBlueSlider1.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider1.setMaximum(255);
        minBlueSlider1.setMinorTickSpacing(1);

        javax.swing.GroupLayout minRGBpanel1Layout = new javax.swing.GroupLayout(minRGBpanel1);
        minRGBpanel1.setLayout(minRGBpanel1Layout);
        minRGBpanel1Layout.setHorizontalGroup(
            minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal1)
                    .addComponent(minGVal1)
                    .addComponent(minBVal1))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        minRGBpanel1Layout.setVerticalGroup(
            minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal1))
                .addGroup(minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal1))
                .addGroup(minRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal1)
                    .addComponent(minBlueSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider1.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider1.setMaximum(255);
        maxRedSlider1.setMinorTickSpacing(1);
        maxRedSlider1.setValue(20);

        maxBlueSlider1.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider1.setMaximum(255);
        maxBlueSlider1.setMinorTickSpacing(1);
        maxBlueSlider1.setValue(255);

        maxGreenSlider1.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider1.setMaximum(255);
        maxGreenSlider1.setMinorTickSpacing(1);
        maxGreenSlider1.setValue(20);

        javax.swing.GroupLayout maxRGBpanel1Layout = new javax.swing.GroupLayout(maxRGBpanel1);
        maxRGBpanel1.setLayout(maxRGBpanel1Layout);
        maxRGBpanel1Layout.setHorizontalGroup(
            maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal1)
                    .addComponent(maxGVal1)
                    .addComponent(maxBVal1))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        maxRGBpanel1Layout.setVerticalGroup(
            maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal1))
                .addGroup(maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal1))
                .addGroup(maxRGBpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal1)
                    .addComponent(maxBlueSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout robotBackThresholdPanelLayout = new javax.swing.GroupLayout(robotBackThresholdPanel);
        robotBackThresholdPanel.setLayout(robotBackThresholdPanelLayout);
        robotBackThresholdPanelLayout.setHorizontalGroup(
            robotBackThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotBackThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotBackThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        robotBackThresholdPanelLayout.setVerticalGroup(
            robotBackThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotBackThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot1SettingsPanel.addTab("Back", robotBackThresholdPanel);

        minRGBpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider2.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider2.setMaximum(255);
        minRedSlider2.setMinorTickSpacing(1);
        minRedSlider2.setValue(100);

        minGreenSlider2.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider2.setMaximum(255);
        minGreenSlider2.setMinorTickSpacing(1);
        minGreenSlider2.setValue(0);

        minBlueSlider2.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider2.setMaximum(255);
        minBlueSlider2.setMinorTickSpacing(1);
        minBlueSlider2.setValue(0);

        javax.swing.GroupLayout minRGBpanel2Layout = new javax.swing.GroupLayout(minRGBpanel2);
        minRGBpanel2.setLayout(minRGBpanel2Layout);
        minRGBpanel2Layout.setHorizontalGroup(
            minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal2)
                    .addComponent(minGVal2)
                    .addComponent(minBVal2))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        minRGBpanel2Layout.setVerticalGroup(
            minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal2))
                .addGroup(minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal2))
                .addGroup(minRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal2)
                    .addComponent(minBlueSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider2.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider2.setMaximum(255);
        maxRedSlider2.setMinorTickSpacing(1);
        maxRedSlider2.setValue(255);

        maxBlueSlider2.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider2.setMaximum(255);
        maxBlueSlider2.setMinorTickSpacing(1);
        maxBlueSlider2.setValue(25);

        maxGreenSlider2.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider2.setMaximum(255);
        maxGreenSlider2.setMinorTickSpacing(1);
        maxGreenSlider2.setValue(25);

        javax.swing.GroupLayout maxRGBpanel2Layout = new javax.swing.GroupLayout(maxRGBpanel2);
        maxRGBpanel2.setLayout(maxRGBpanel2Layout);
        maxRGBpanel2Layout.setHorizontalGroup(
            maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal2)
                    .addComponent(maxGVal2)
                    .addComponent(maxBVal2))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        maxRGBpanel2Layout.setVerticalGroup(
            maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal2))
                .addGroup(maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal2))
                .addGroup(maxRGBpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal2)
                    .addComponent(maxBlueSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout cakesThresholdPanelLayout = new javax.swing.GroupLayout(cakesThresholdPanel);
        cakesThresholdPanel.setLayout(cakesThresholdPanelLayout);
        cakesThresholdPanelLayout.setHorizontalGroup(
            cakesThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakesThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cakesThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        cakesThresholdPanelLayout.setVerticalGroup(
            cakesThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakesThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot1SettingsPanel.addTab("Cakes", cakesThresholdPanel);

        minRGBpanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider3.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider3.setMaximum(255);
        minRedSlider3.setMinorTickSpacing(1);
        minRedSlider3.setValue(150);

        minGreenSlider3.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider3.setMaximum(255);
        minGreenSlider3.setMinorTickSpacing(1);
        minGreenSlider3.setValue(150);

        minBlueSlider3.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider3.setMaximum(255);
        minBlueSlider3.setMinorTickSpacing(1);
        minBlueSlider3.setValue(150);

        javax.swing.GroupLayout minRGBpanel3Layout = new javax.swing.GroupLayout(minRGBpanel3);
        minRGBpanel3.setLayout(minRGBpanel3Layout);
        minRGBpanel3Layout.setHorizontalGroup(
            minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal3)
                    .addComponent(minGVal3)
                    .addComponent(minBVal3))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        minRGBpanel3Layout.setVerticalGroup(
            minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal3))
                .addGroup(minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal3))
                .addGroup(minRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal3)
                    .addComponent(minBlueSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider3.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider3.setMaximum(255);
        maxRedSlider3.setMinorTickSpacing(1);
        maxRedSlider3.setValue(255);

        maxBlueSlider3.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider3.setMaximum(255);
        maxBlueSlider3.setMinorTickSpacing(1);
        maxBlueSlider3.setValue(255);

        maxGreenSlider3.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider3.setMaximum(255);
        maxGreenSlider3.setMinorTickSpacing(1);
        maxGreenSlider3.setValue(255);

        javax.swing.GroupLayout maxRGBpanel3Layout = new javax.swing.GroupLayout(maxRGBpanel3);
        maxRGBpanel3.setLayout(maxRGBpanel3Layout);
        maxRGBpanel3Layout.setHorizontalGroup(
            maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal3)
                    .addComponent(maxGVal3)
                    .addComponent(maxBVal3))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        maxRGBpanel3Layout.setVerticalGroup(
            maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal3))
                .addGroup(maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal3))
                .addGroup(maxRGBpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal3)
                    .addComponent(maxBlueSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout obstacleThresholdPanelLayout = new javax.swing.GroupLayout(obstacleThresholdPanel);
        obstacleThresholdPanel.setLayout(obstacleThresholdPanelLayout);
        obstacleThresholdPanelLayout.setHorizontalGroup(
            obstacleThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obstacleThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        obstacleThresholdPanelLayout.setVerticalGroup(
            obstacleThresholdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot1SettingsPanel.addTab("Obstacles", obstacleThresholdPanel);

        javax.swing.GroupLayout miscPanelLayout = new javax.swing.GroupLayout(miscPanel);
        miscPanel.setLayout(miscPanelLayout);
        miscPanelLayout.setHorizontalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        miscPanelLayout.setVerticalGroup(
            miscPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        robot1SettingsPanel.addTab("Misc", miscPanel);

        robot1SettingsPanel.setBounds(0, 130, 340, 340);
        thresholdsLayeredPane.add(robot1SettingsPanel, javax.swing.JLayeredPane.PALETTE_LAYER);

        minRGBpanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider4.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider4.setMaximum(255);
        minRedSlider4.setMinorTickSpacing(1);
        minRedSlider4.setValue(0);

        minGreenSlider4.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider4.setMaximum(255);
        minGreenSlider4.setMinorTickSpacing(1);
        minGreenSlider4.setValue(70);

        minBlueSlider4.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider4.setMaximum(255);
        minBlueSlider4.setMinorTickSpacing(1);
        minBlueSlider4.setValue(0);

        javax.swing.GroupLayout minRGBpanel4Layout = new javax.swing.GroupLayout(minRGBpanel4);
        minRGBpanel4.setLayout(minRGBpanel4Layout);
        minRGBpanel4Layout.setHorizontalGroup(
            minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal4)
                    .addComponent(minGVal4)
                    .addComponent(minBVal4))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        minRGBpanel4Layout.setVerticalGroup(
            minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal4))
                .addGroup(minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal4))
                .addGroup(minRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal4)
                    .addComponent(minBlueSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider4.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider4.setMaximum(255);
        maxRedSlider4.setMinorTickSpacing(1);
        maxRedSlider4.setValue(70);

        maxBlueSlider4.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider4.setMaximum(255);
        maxBlueSlider4.setMinorTickSpacing(1);
        maxBlueSlider4.setValue(90);

        maxGreenSlider4.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider4.setMaximum(255);
        maxGreenSlider4.setMinorTickSpacing(1);
        maxGreenSlider4.setValue(255);

        javax.swing.GroupLayout maxRGBpanel4Layout = new javax.swing.GroupLayout(maxRGBpanel4);
        maxRGBpanel4.setLayout(maxRGBpanel4Layout);
        maxRGBpanel4Layout.setHorizontalGroup(
            maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal4)
                    .addComponent(maxGVal4)
                    .addComponent(maxBVal4))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        maxRGBpanel4Layout.setVerticalGroup(
            maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal4))
                .addGroup(maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal4))
                .addGroup(maxRGBpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal4)
                    .addComponent(maxBlueSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout robotFrontThresholdPanel1Layout = new javax.swing.GroupLayout(robotFrontThresholdPanel1);
        robotFrontThresholdPanel1.setLayout(robotFrontThresholdPanel1Layout);
        robotFrontThresholdPanel1Layout.setHorizontalGroup(
            robotFrontThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotFrontThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotFrontThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maxRGBpanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minRGBpanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        robotFrontThresholdPanel1Layout.setVerticalGroup(
            robotFrontThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotFrontThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot2SettingsPanel.addTab("Front", robotFrontThresholdPanel1);

        minRGBpanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider5.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider5.setMaximum(255);
        minRedSlider5.setMinorTickSpacing(1);
        minRedSlider5.setValue(0);

        minGreenSlider5.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider5.setMaximum(255);
        minGreenSlider5.setMinorTickSpacing(1);
        minGreenSlider5.setValue(0);

        minBlueSlider5.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider5.setMaximum(255);
        minBlueSlider5.setMinorTickSpacing(1);

        javax.swing.GroupLayout minRGBpanel5Layout = new javax.swing.GroupLayout(minRGBpanel5);
        minRGBpanel5.setLayout(minRGBpanel5Layout);
        minRGBpanel5Layout.setHorizontalGroup(
            minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal5)
                    .addComponent(minGVal5)
                    .addComponent(minBVal5))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        minRGBpanel5Layout.setVerticalGroup(
            minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal5))
                .addGroup(minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal5))
                .addGroup(minRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal5)
                    .addComponent(minBlueSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider5.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider5.setMaximum(255);
        maxRedSlider5.setMinorTickSpacing(1);
        maxRedSlider5.setValue(20);

        maxBlueSlider5.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider5.setMaximum(255);
        maxBlueSlider5.setMinorTickSpacing(1);
        maxBlueSlider5.setValue(255);

        maxGreenSlider5.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider5.setMaximum(255);
        maxGreenSlider5.setMinorTickSpacing(1);
        maxGreenSlider5.setValue(20);

        javax.swing.GroupLayout maxRGBpanel5Layout = new javax.swing.GroupLayout(maxRGBpanel5);
        maxRGBpanel5.setLayout(maxRGBpanel5Layout);
        maxRGBpanel5Layout.setHorizontalGroup(
            maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal5)
                    .addComponent(maxGVal5)
                    .addComponent(maxBVal5))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        maxRGBpanel5Layout.setVerticalGroup(
            maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal5))
                .addGroup(maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal5))
                .addGroup(maxRGBpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal5)
                    .addComponent(maxBlueSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout robotBackThresholdPanel1Layout = new javax.swing.GroupLayout(robotBackThresholdPanel1);
        robotBackThresholdPanel1.setLayout(robotBackThresholdPanel1Layout);
        robotBackThresholdPanel1Layout.setHorizontalGroup(
            robotBackThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotBackThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotBackThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        robotBackThresholdPanel1Layout.setVerticalGroup(
            robotBackThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotBackThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot2SettingsPanel.addTab("Back", robotBackThresholdPanel1);

        minRGBpanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider6.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider6.setMaximum(255);
        minRedSlider6.setMinorTickSpacing(1);
        minRedSlider6.setValue(100);

        minGreenSlider6.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider6.setMaximum(255);
        minGreenSlider6.setMinorTickSpacing(1);
        minGreenSlider6.setValue(0);

        minBlueSlider6.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider6.setMaximum(255);
        minBlueSlider6.setMinorTickSpacing(1);
        minBlueSlider6.setValue(0);

        javax.swing.GroupLayout minRGBpanel6Layout = new javax.swing.GroupLayout(minRGBpanel6);
        minRGBpanel6.setLayout(minRGBpanel6Layout);
        minRGBpanel6Layout.setHorizontalGroup(
            minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal6)
                    .addComponent(minGVal6)
                    .addComponent(minBVal6))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        minRGBpanel6Layout.setVerticalGroup(
            minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal6))
                .addGroup(minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal6))
                .addGroup(minRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal6)
                    .addComponent(minBlueSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider6.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider6.setMaximum(255);
        maxRedSlider6.setMinorTickSpacing(1);
        maxRedSlider6.setValue(255);

        maxBlueSlider6.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider6.setMaximum(255);
        maxBlueSlider6.setMinorTickSpacing(1);
        maxBlueSlider6.setValue(25);

        maxGreenSlider6.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider6.setMaximum(255);
        maxGreenSlider6.setMinorTickSpacing(1);
        maxGreenSlider6.setValue(25);

        javax.swing.GroupLayout maxRGBpanel6Layout = new javax.swing.GroupLayout(maxRGBpanel6);
        maxRGBpanel6.setLayout(maxRGBpanel6Layout);
        maxRGBpanel6Layout.setHorizontalGroup(
            maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal6)
                    .addComponent(maxGVal6)
                    .addComponent(maxBVal6))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        maxRGBpanel6Layout.setVerticalGroup(
            maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal6))
                .addGroup(maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal6))
                .addGroup(maxRGBpanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal6)
                    .addComponent(maxBlueSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout cakesThresholdPanel1Layout = new javax.swing.GroupLayout(cakesThresholdPanel1);
        cakesThresholdPanel1.setLayout(cakesThresholdPanel1Layout);
        cakesThresholdPanel1Layout.setHorizontalGroup(
            cakesThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakesThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cakesThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        cakesThresholdPanel1Layout.setVerticalGroup(
            cakesThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cakesThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot2SettingsPanel.addTab("Cakes", cakesThresholdPanel1);

        minRGBpanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider7.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider7.setMaximum(255);
        minRedSlider7.setMinorTickSpacing(1);
        minRedSlider7.setValue(150);

        minGreenSlider7.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider7.setMaximum(255);
        minGreenSlider7.setMinorTickSpacing(1);
        minGreenSlider7.setValue(150);

        minBlueSlider7.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider7.setMaximum(255);
        minBlueSlider7.setMinorTickSpacing(1);
        minBlueSlider7.setValue(150);

        javax.swing.GroupLayout minRGBpanel7Layout = new javax.swing.GroupLayout(minRGBpanel7);
        minRGBpanel7.setLayout(minRGBpanel7Layout);
        minRGBpanel7Layout.setHorizontalGroup(
            minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal7)
                    .addComponent(minGVal7)
                    .addComponent(minBVal7))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        minRGBpanel7Layout.setVerticalGroup(
            minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal7))
                .addGroup(minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal7))
                .addGroup(minRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal7)
                    .addComponent(minBlueSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider7.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider7.setMaximum(255);
        maxRedSlider7.setMinorTickSpacing(1);
        maxRedSlider7.setValue(255);

        maxBlueSlider7.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider7.setMaximum(255);
        maxBlueSlider7.setMinorTickSpacing(1);
        maxBlueSlider7.setValue(255);

        maxGreenSlider7.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider7.setMaximum(255);
        maxGreenSlider7.setMinorTickSpacing(1);
        maxGreenSlider7.setValue(255);

        javax.swing.GroupLayout maxRGBpanel7Layout = new javax.swing.GroupLayout(maxRGBpanel7);
        maxRGBpanel7.setLayout(maxRGBpanel7Layout);
        maxRGBpanel7Layout.setHorizontalGroup(
            maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal7)
                    .addComponent(maxGVal7)
                    .addComponent(maxBVal7))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        maxRGBpanel7Layout.setVerticalGroup(
            maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal7))
                .addGroup(maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal7))
                .addGroup(maxRGBpanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal7)
                    .addComponent(maxBlueSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout obstacleThresholdPanel1Layout = new javax.swing.GroupLayout(obstacleThresholdPanel1);
        obstacleThresholdPanel1.setLayout(obstacleThresholdPanel1Layout);
        obstacleThresholdPanel1Layout.setHorizontalGroup(
            obstacleThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obstacleThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minRGBpanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxRGBpanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        obstacleThresholdPanel1Layout.setVerticalGroup(
            obstacleThresholdPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minRGBpanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maxRGBpanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        robot2SettingsPanel.addTab("Obstacles", obstacleThresholdPanel1);

        javax.swing.GroupLayout miscPanel1Layout = new javax.swing.GroupLayout(miscPanel1);
        miscPanel1.setLayout(miscPanel1Layout);
        miscPanel1Layout.setHorizontalGroup(
            miscPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        miscPanel1Layout.setVerticalGroup(
            miscPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        robot2SettingsPanel.addTab("Misc", miscPanel1);

        robot2SettingsPanel.setBounds(0, 130, 340, 340);
        thresholdsLayeredPane.add(robot2SettingsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(robot1RadioButton);
        robot1RadioButton.setText("B.E.R.T.A.");
        robot1RadioButton.setBounds(60, 10, 93, -1);
        thresholdsLayeredPane.add(robot1RadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(robot2RadioButton);
        robot2RadioButton.setText("P.R.O.P.");
        robot2RadioButton.setBounds(200, 10, 93, -1);
        thresholdsLayeredPane.add(robot2RadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        commonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Common"));
        commonPanel.setLayout(new java.awt.GridBagLayout());

        bufzoneSlider2.setMaximum(50);
        bufzoneSlider2.setValue(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        commonPanel.add(bufzoneSlider2, gridBagConstraints);

        jLabel1.setText("Bufferzone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        commonPanel.add(jLabel1, gridBagConstraints);

        minRGBpanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Min RGB"));

        minRedSlider8.setBackground(new java.awt.Color(255, 0, 0));
        minRedSlider8.setMaximum(255);
        minRedSlider8.setMinorTickSpacing(1);
        minRedSlider8.setValue(150);

        minGreenSlider8.setBackground(new java.awt.Color(0, 255, 0));
        minGreenSlider8.setMaximum(255);
        minGreenSlider8.setMinorTickSpacing(1);
        minGreenSlider8.setValue(150);

        minBlueSlider8.setBackground(new java.awt.Color(0, 0, 255));
        minBlueSlider8.setMaximum(255);
        minBlueSlider8.setMinorTickSpacing(1);
        minBlueSlider8.setValue(150);

        javax.swing.GroupLayout minRGBpanel8Layout = new javax.swing.GroupLayout(minRGBpanel8);
        minRGBpanel8.setLayout(minRGBpanel8Layout);
        minRGBpanel8Layout.setHorizontalGroup(
            minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBlueSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGreenSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRedSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRVal8)
                    .addComponent(minGVal8)
                    .addComponent(minBVal8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        minRGBpanel8Layout.setVerticalGroup(
            minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minRGBpanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minRedSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minRVal8))
                .addGroup(minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGreenSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGVal8))
                .addGroup(minRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minBVal8)
                    .addComponent(minBlueSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        maxRGBpanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Max RGB"));

        maxRedSlider8.setBackground(new java.awt.Color(255, 0, 0));
        maxRedSlider8.setMaximum(255);
        maxRedSlider8.setMinorTickSpacing(1);
        maxRedSlider8.setValue(255);

        maxBlueSlider8.setBackground(new java.awt.Color(0, 0, 255));
        maxBlueSlider8.setMaximum(255);
        maxBlueSlider8.setMinorTickSpacing(1);
        maxBlueSlider8.setValue(255);

        maxGreenSlider8.setBackground(new java.awt.Color(0, 255, 0));
        maxGreenSlider8.setMaximum(255);
        maxGreenSlider8.setMinorTickSpacing(1);
        maxGreenSlider8.setValue(255);

        javax.swing.GroupLayout maxRGBpanel8Layout = new javax.swing.GroupLayout(maxRGBpanel8);
        maxRGBpanel8.setLayout(maxRGBpanel8Layout);
        maxRGBpanel8Layout.setHorizontalGroup(
            maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBlueSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGreenSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRedSlider8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRVal8)
                    .addComponent(maxGVal8)
                    .addComponent(maxBVal8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maxRGBpanel8Layout.setVerticalGroup(
            maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maxRGBpanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxRedSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxRVal8))
                .addGroup(maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxGreenSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxGVal8))
                .addGroup(maxRGBpanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxBVal8)
                    .addComponent(maxBlueSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Obstacles");

        javax.swing.GroupLayout obstacleThresholdPanel2Layout = new javax.swing.GroupLayout(obstacleThresholdPanel2);
        obstacleThresholdPanel2.setLayout(obstacleThresholdPanel2Layout);
        obstacleThresholdPanel2Layout.setHorizontalGroup(
            obstacleThresholdPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obstacleThresholdPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(maxRGBpanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minRGBpanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        obstacleThresholdPanel2Layout.setVerticalGroup(
            obstacleThresholdPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obstacleThresholdPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(obstacleThresholdPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(obstacleThresholdPanel2Layout.createSequentialGroup()
                        .addComponent(minRGBpanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxRGBpanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        commonPanel.add(obstacleThresholdPanel2, gridBagConstraints);

        commonPanel.setBounds(0, 130, 340, 340);
        thresholdsLayeredPane.add(commonPanel, javax.swing.JLayeredPane.POPUP_LAYER);

        buttonGroup1.add(commonRadioButton);
        commonRadioButton.setText("Common settings");
        commonRadioButton.setBounds(113, 40, 120, -1);
        thresholdsLayeredPane.add(commonRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thresholdsLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(thresholdsLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JSlider bufzoneSlider2;
    private javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JPanel cakesThresholdPanel;
    javax.swing.JPanel cakesThresholdPanel1;
    private javax.swing.JPanel commonPanel;
    private javax.swing.JRadioButton commonRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel maxBVal;
    private javax.swing.JLabel maxBVal1;
    private javax.swing.JLabel maxBVal2;
    private javax.swing.JLabel maxBVal3;
    private javax.swing.JLabel maxBVal4;
    private javax.swing.JLabel maxBVal5;
    private javax.swing.JLabel maxBVal6;
    private javax.swing.JLabel maxBVal7;
    private javax.swing.JLabel maxBVal8;
    javax.swing.JSlider maxBlueSlider;
    javax.swing.JSlider maxBlueSlider1;
    javax.swing.JSlider maxBlueSlider2;
    javax.swing.JSlider maxBlueSlider3;
    javax.swing.JSlider maxBlueSlider4;
    javax.swing.JSlider maxBlueSlider5;
    javax.swing.JSlider maxBlueSlider6;
    javax.swing.JSlider maxBlueSlider7;
    javax.swing.JSlider maxBlueSlider8;
    private javax.swing.JLabel maxGVal;
    private javax.swing.JLabel maxGVal1;
    private javax.swing.JLabel maxGVal2;
    private javax.swing.JLabel maxGVal3;
    private javax.swing.JLabel maxGVal4;
    private javax.swing.JLabel maxGVal5;
    private javax.swing.JLabel maxGVal6;
    private javax.swing.JLabel maxGVal7;
    private javax.swing.JLabel maxGVal8;
    javax.swing.JSlider maxGreenSlider;
    javax.swing.JSlider maxGreenSlider1;
    javax.swing.JSlider maxGreenSlider2;
    javax.swing.JSlider maxGreenSlider3;
    javax.swing.JSlider maxGreenSlider4;
    javax.swing.JSlider maxGreenSlider5;
    javax.swing.JSlider maxGreenSlider6;
    javax.swing.JSlider maxGreenSlider7;
    javax.swing.JSlider maxGreenSlider8;
    javax.swing.JPanel maxRGBpanel;
    javax.swing.JPanel maxRGBpanel1;
    javax.swing.JPanel maxRGBpanel2;
    javax.swing.JPanel maxRGBpanel3;
    javax.swing.JPanel maxRGBpanel4;
    javax.swing.JPanel maxRGBpanel5;
    javax.swing.JPanel maxRGBpanel6;
    javax.swing.JPanel maxRGBpanel7;
    javax.swing.JPanel maxRGBpanel8;
    private javax.swing.JLabel maxRVal;
    private javax.swing.JLabel maxRVal1;
    private javax.swing.JLabel maxRVal2;
    private javax.swing.JLabel maxRVal3;
    private javax.swing.JLabel maxRVal4;
    private javax.swing.JLabel maxRVal5;
    private javax.swing.JLabel maxRVal6;
    private javax.swing.JLabel maxRVal7;
    private javax.swing.JLabel maxRVal8;
    javax.swing.JSlider maxRedSlider;
    javax.swing.JSlider maxRedSlider1;
    javax.swing.JSlider maxRedSlider2;
    javax.swing.JSlider maxRedSlider3;
    javax.swing.JSlider maxRedSlider4;
    javax.swing.JSlider maxRedSlider5;
    javax.swing.JSlider maxRedSlider6;
    javax.swing.JSlider maxRedSlider7;
    javax.swing.JSlider maxRedSlider8;
    private javax.swing.JLabel minBVal;
    private javax.swing.JLabel minBVal1;
    private javax.swing.JLabel minBVal2;
    private javax.swing.JLabel minBVal3;
    private javax.swing.JLabel minBVal4;
    private javax.swing.JLabel minBVal5;
    private javax.swing.JLabel minBVal6;
    private javax.swing.JLabel minBVal7;
    private javax.swing.JLabel minBVal8;
    javax.swing.JSlider minBlueSlider;
    javax.swing.JSlider minBlueSlider1;
    javax.swing.JSlider minBlueSlider2;
    javax.swing.JSlider minBlueSlider3;
    javax.swing.JSlider minBlueSlider4;
    javax.swing.JSlider minBlueSlider5;
    javax.swing.JSlider minBlueSlider6;
    javax.swing.JSlider minBlueSlider7;
    javax.swing.JSlider minBlueSlider8;
    private javax.swing.JLabel minGVal;
    private javax.swing.JLabel minGVal1;
    private javax.swing.JLabel minGVal2;
    private javax.swing.JLabel minGVal3;
    private javax.swing.JLabel minGVal4;
    private javax.swing.JLabel minGVal5;
    private javax.swing.JLabel minGVal6;
    private javax.swing.JLabel minGVal7;
    private javax.swing.JLabel minGVal8;
    javax.swing.JSlider minGreenSlider;
    javax.swing.JSlider minGreenSlider1;
    javax.swing.JSlider minGreenSlider2;
    javax.swing.JSlider minGreenSlider3;
    javax.swing.JSlider minGreenSlider4;
    javax.swing.JSlider minGreenSlider5;
    javax.swing.JSlider minGreenSlider6;
    javax.swing.JSlider minGreenSlider7;
    javax.swing.JSlider minGreenSlider8;
    javax.swing.JPanel minRGBpanel;
    javax.swing.JPanel minRGBpanel1;
    javax.swing.JPanel minRGBpanel2;
    javax.swing.JPanel minRGBpanel3;
    javax.swing.JPanel minRGBpanel4;
    javax.swing.JPanel minRGBpanel5;
    javax.swing.JPanel minRGBpanel6;
    javax.swing.JPanel minRGBpanel7;
    javax.swing.JPanel minRGBpanel8;
    private javax.swing.JLabel minRVal;
    private javax.swing.JLabel minRVal1;
    private javax.swing.JLabel minRVal2;
    private javax.swing.JLabel minRVal3;
    private javax.swing.JLabel minRVal4;
    private javax.swing.JLabel minRVal5;
    private javax.swing.JLabel minRVal6;
    private javax.swing.JLabel minRVal7;
    private javax.swing.JLabel minRVal8;
    javax.swing.JSlider minRedSlider;
    javax.swing.JSlider minRedSlider1;
    javax.swing.JSlider minRedSlider2;
    javax.swing.JSlider minRedSlider3;
    javax.swing.JSlider minRedSlider4;
    javax.swing.JSlider minRedSlider5;
    javax.swing.JSlider minRedSlider6;
    javax.swing.JSlider minRedSlider7;
    javax.swing.JSlider minRedSlider8;
    javax.swing.JPanel miscPanel;
    javax.swing.JPanel miscPanel1;
    javax.swing.JPanel obstacleThresholdPanel;
    javax.swing.JPanel obstacleThresholdPanel1;
    javax.swing.JPanel obstacleThresholdPanel2;
    private javax.swing.JRadioButton robot1RadioButton;
    javax.swing.JTabbedPane robot1SettingsPanel;
    private javax.swing.JRadioButton robot2RadioButton;
    javax.swing.JTabbedPane robot2SettingsPanel;
    javax.swing.JPanel robotBackThresholdPanel;
    javax.swing.JPanel robotBackThresholdPanel1;
    javax.swing.JPanel robotFrontThresholdPanel;
    javax.swing.JPanel robotFrontThresholdPanel1;
    private javax.swing.JLayeredPane thresholdsLayeredPane;
    // End of variables declaration//GEN-END:variables

}
